### ISSUE TITLE
Problematic Debug Logging Configuration

### ISSUE THREAD

**Issue by Morikko** [jellyfin/jellyfin.org#1125]
On https://github.com/jellyfin/jellyfin.org/blob/master/docs/general/administration/troubleshooting.md#debug-logging, the default configuration for debug is:

```
{
    "Serilog": {
        "MinimumLevel": {
            "Default": "Debug",
            "Override": {
                "": "Debug"
            }
        }
    }
}
```

but this triggers on docker jellyfin 10.9.11:

```
[2024-09-21 09:21:11.083 +00:00] [FTL] [1] : Failed to create/read logger configuration
System.ArgumentException: A source source must be provided. (Parameter 'source')
   at Serilog.Configuration.LoggerMinimumLevelConfiguration.Override(String source, LoggingLevelSwitch levelSwitch)
   at Serilog.Settings.Configuration.ConfigurationReader.<>c__DisplayClass11_1.<ApplyMinimumLevel>b__3(LoggerMinimumLevelConfiguration configuration, LoggingLevelSwitch levelSwitch)
   at Serilog.Settings.Configuration.ConfigurationReader.<>c__DisplayClass11_0.<ApplyMinimumLevel>g__ApplyMinimumLevelConfiguration|1(IConfigurationSection directive, Action`2 applyConfigAction)
   at Serilog.Settings.Configuration.ConfigurationReader.ApplyMinimumLevel(LoggerConfiguration loggerConfiguration)
   at Serilog.Settings.Configuration.ConfigurationReader.Configure(LoggerConfiguration loggerConfiguration)
   at Serilog.Configuration.LoggerSettingsConfiguration.Settings(ILoggerSettings settings)
   at Serilog.ConfigurationLoggerConfigurationExtensions.Configuration(LoggerSettingsConfiguration settingConfiguration, IConfiguration configuration, ConfigurationReaderOptions readerOptions)
   at Jellyfin.Server.Helpers.StartupHelpers.InitializeLoggingFramework(IConfiguration configuration, IApplicationPaths appPaths)
```

I suspect the empty string to be problematic.

Alternative valid configurations:

```
{
    "Serilog": {
        "MinimumLevel": "Debug"
    }
}
```

or

```
"MinimumLevel": {
    "Default": "Debug",
    "Override": {
        "Microsoft": "Debug",
        "System": "Debug"
    }
}
```

**Comment by szotsaki** [comment]
It's still an issue that is misleading readers. The provided example doesn't work.

I can confirm that after replacing the empty string with the above `"Override"` section, debug messages are seen.

**Comment by BotBlake** [comment]
@JPVenson I dont know anything about server logging mechanics, but does that seem good to you?

**Comment by JPVenson** [comment]
Our documentation only relates to the last stable version which is as of today 10.10 and not 10.09.

Please upgrade to 10.10 and recheck if the config still does not work.

**Comment by szotsaki** [comment]
I tested it with the latest Jellyfin version and it shows the same backtrace and the same fix applies.

```
$ jellyfin --version
Jellyfin.Server 10.10.7.0
```

Works:
```json
{
    "Serilog": {
        "MinimumLevel": {
            "Default": "Debug",
            "Override": {
                "Microsoft": "Debug",
                "System": "Debug",
                "Jellyfin.Plugin.Dlna": "Debug"
            }
        }
    }
}
```

Doesn't work:
```json
{
    "Serilog": {
        "MinimumLevel": {
            "Default": "Debug",
            "Override": {
                "": "Debug"
            }
        }
    }
}
```

**Comment by Termuellinator** [comment]
if only i had searched here earlier - i've just encountered exactly this issue.
After almost three hours of troubleshooting on why i couldn't get debug output, two main things are wrong:
- the example needs to be
```
"MinimumLevel": {
    "Default": "Debug",
    "Override": {
        "Microsoft": "Debug",
        "System": "Debug"
    }
}
```
- And at least on my debian install, `/etc/jellyfin/logging.json` doesn't seem to actually override `/etc/jellyfin/logging.default.json`. Only if i make changes to `logging.default.json` are they honored.

I wanted to create a PR for that, but would like to get some input first if the latter is debian specific or if that is true for other installation methods, too?

**Comment by BotBlake** [comment]
Can anyone confirm this issue still existing on Jellyfin 10.11.x?
A lot has changed since 😅
